#!/usr/bin/env sh

. config

dwm_conf_path="$HOME/suckless/dwm/src"
st_conf_path="$HOME/suckless/st/src/"
dwmblocks_conf_path="$HOME/suckless/dwmblocks"
dmenu_conf_path="$HOME/suckless/dmenu/src"
dot_config_path="$HOME/.config/"

dwm_script_prefix="dwm_"
dm_script_prefix="dm_"

conf_list="dwm\ndwmblocks\nst\ndmenu\n"

for i in "$dot_config_path"*
    do
        tmp=$(echo "$i" | sed 's|'"$dot_config_path"'||')
        conf_list="$conf_list$tmp\n"
    done

dwm_script_list=""
dm_script_list=""
g_script_list=""

for i in "$SCRIPTPATH"*
do
    tmp=$(echo "$i" | sed 's|'"$SCRIPTPATH"'||')
    case $tmp in
        $dwm_script_prefix*)
            dwm_script_list="$dwm_script_list$tmp\n";;
        $dm_script_prefix*)
            tmp=$(echo "$i" | sed 's|'"$SCRIPTPATH"'||')
            dm_script_list="$dm_script_list$tmp\n";;
        *config*)
            ;;
        *)
            g_script_list="$g_script_list$tmp\n"
            ;;
    esac
done


default(){

    sel_def=$(printf 'Configs\nScripts'|sort | dmenu -p Edit:)
    case "$sel_def" in
        Configs) 
            edit_configs;;
        Scripts) 
            select_script_group;;
        *)
            exit 0
            ;;
    esac
    
}
select_script_group(){

    sc_group="$(printf 'dwm\ndmenu\ngeneral\nconfig' | sort | dmenu -p 'Script Group')"
    case "$sc_group" in
        dwm) 
            edit_dwm_scripts;;
        dmenu) 
            edit_dmenu_scripts;;
        general) 
            edit_general_scripts;;
        config) 
            edit_script_config;;
        *)
            exit 0;;
    esac
    
}

edit_dwm_scripts(){
    dwm_script=$(printf '%b' "$dwm_script_list"| dmenu -p 'dwm scripts:')
    if [ -n "$dwm_script" ]; then
        eval "$TERMEDIT $SCRIPTPATH$dwm_script"
        exit 0
    fi
}
edit_dmenu_scripts(){

    dm_script=$(printf '%b' "$dm_script_list"| dmenu -p 'dmenu scripts:')
    if [ -n "$dm_script" ]; then
        eval "$TERMEDIT $SCRIPTPATH$dm_script"
        exit 0
    fi
}
edit_general_scripts(){

    g_script=$(printf '%b' "$g_script_list" | dmenu -p 'General Scripts:')
    if [ -n "$g_script" ]; then
        eval "$TERMEDIT $SCRIPTPATH$g_script"
        exit 0
    fi
}
edit_script_config(){
    eval "$TERMEDIT $SCRIPTPATH'config'"
exit 0;
}
edit_configs(){
    conf_edit="$(printf '%b' "$conf_list" |sort | dmenu -p 'Select config to edit')"

    case "$conf_edit" in
       dwm)
           conf_path="$dwm_conf_path";;
       dwmblocks)
           conf_path="$dwmblocks_conf_path";;
       st)
           conf_path="$st_conf_path";;
       dmenu)
           conf_path="$dmenu_conf_path";;
       *)
           if [ -z "$conf_edit" ]; then
               exit 0;
           fi
           if echo "$conf_list" | grep -q "$conf_edit"; then
            conf_path="$dot_config_path/$conf_edit"
           else
               echo "Config does not exist"
            exit 1
           fi;;
    esac
    eval "$TERMEDIT $conf_path"

}


if [ $# -eq 0 ]; then
    default
else
    "$@"
fi
exit 0
