#!/bin/sh
source config

case "$(date '+%I')" in
    "01") clk_icon="" ;;
    "02") clk_icon="" ;;
    "03") clk_icon="" ;;
    "04") clk_icon="" ;;
    "05") clk_icon="" ;;
    "06") clk_icon="" ;;
    "07") clk_icon="" ;;
    "08") clk_icon="" ;;
    "09") clk_icon="" ;;
    "10") clk_icon="" ;;
    "11") clk_icon="" ;;
    "12") clk_icon="" ;;
esac

time_hour="$(date '+%H')"
if [[ time_hour -gt DT_DUSK ]]; then
    icon_color="$color_dusk" # #9F3379
elif [[ time_hour -gt DT_EVENING ]]; then
    icon_color="$color_evening" # #A7408B
elif [[ time_hour -gt DT_AFTERNOON ]]; then
    icon_color="$color_afternoon" # #C83C63
elif [[ time_hour -gt DT_MORNING ]]; then
    icon_color="$color_morning" # #F34C5E
elif [[ time_hour -gt DT_DAWN ]]; then
    icon_color="$color_dawn" # #FF8120
else
    icon_color="$color_dusk" # #9F3379
fi

calendar_icon=""
day_info="$(date '+%d.%m.%y %a')"
clk_info="$(date '+%H:%M')"

printf "%s%s %s %s %s%s\n" "$icon_color" "$calendar_icon" "$day_info" "$clk_icon" "$clk_info" "$s2d_reset_color" && exit 0
